[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "properties/=../../../contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "solmate/=lib/solmate/src/"
]